'use strict';
const $=id=>document.getElementById(id), SETTINGS='cyphonic-sync-settings-v2', CACHE='cyphonic-sync-cache-v2';
let entries=[];
const settings=()=>{try{return JSON.parse(localStorage.getItem(SETTINGS)||'{}')}catch{return{}}};
const saveSettings=x=>localStorage.setItem(SETTINGS,JSON.stringify(x));
const fmt=x=>x?new Date(x).toLocaleString('ja-JP'):'不明';
const clamp=n=>Math.max(0,Math.min(100,Number(n)||0));
function rate(arr){if(arr.length<2)return null;let start=0;for(let i=1;i<arr.length;i++)if(arr[i].weekRemaining>arr[i-1].weekRemaining+1||arr[i].weekResetAt!==arr[i-1].weekResetAt)start=i;const a=arr[start],b=arr.at(-1),h=(Date.parse(b.capturedAt)-Date.parse(a.capturedAt))/36e5;return h>0&&a.weekRemaining>b.weekRemaining?(a.weekRemaining-b.weekRemaining)/h:null}
function burn24(arr){const cutoff=Date.now()-864e5, recent=arr.filter(x=>Date.parse(x.capturedAt)>=cutoff);if(recent.length<2)return null;return Math.max(0,recent[0].weekRemaining-recent.at(-1).weekRemaining)}
function render(){const last=entries.at(-1);$('five-value').textContent=last?last.fiveRemaining+'%':'—';$('week-value').textContent=last?last.weekRemaining+'%':'—';$('five-bar').value=last?last.fiveRemaining:0;$('week-bar').value=last?last.weekRemaining:0;$('five-reset').textContent='リセット：'+fmt(last?.fiveResetAt);$('week-reset').textContent='リセット：'+fmt(last?.weekResetAt);$('confidence').textContent=last?Math.round((last.confidence||0)*100)+'%':'—';const r=rate(entries),b24=burn24(entries);$('burnRate').textContent=r?r.toFixed(2)+'%/h':'—';$('burn24').textContent=b24!=null?b24.toFixed(1)+'%':'—';let exhaust=last&&r?Date.parse(last.capturedAt)+last.weekRemaining/r*36e5:null;$('forecast').textContent=exhaust?'週間枠の枯渇予測：'+fmt(exhaust):'枯渇予測：記録不足';let d='データ待ち',reason='同期データがありません。';if(last){const stale=Date.now()-Date.parse(last.capturedAt)>6*36e5;const danger=last.fiveRemaining<=15||last.weekRemaining<=15||(exhaust&&last.weekResetAt&&exhaust<Date.parse(last.weekResetAt));d=stale?'計画運用':danger?'温存':last.fiveRemaining>=50&&last.weekRemaining>=50?'GO':'計画運用';reason=stale?'最終取得が古いです。PCでUsage画面を開いて更新してください。':danger?'残量が少ない、または週間リセット前に枯渇するペースです。':'CYPHONICの重い作業に使える余力を残量と消費速度から判定しています。'}$('decision').textContent=d;$('reason').textContent=reason;$('history').replaceChildren();entries.slice(-100).reverse().forEach(e=>{const tr=document.createElement('tr');[fmt(e.capturedAt),e.fiveRemaining+'%',e.weekRemaining+'%',Math.round((e.confidence||0)*100)+'%'].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});$('history').append(tr)});drawChart();}
function drawChart(){const svg=$('chart');svg.replaceChildren();const add=(tag,a,t)=>{const n=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.entries(a).forEach(([k,v])=>n.setAttribute(k,v));if(t!=null)n.textContent=t;svg.append(n)};const now=Date.now(),start=now-7*864e5;[0,50,100].forEach(n=>{const y=180-n*1.5;add('line',{x1:40,y1:y,x2:625,y2:y,stroke:'#30445f'});add('text',{x:6,y:y+4,fill:'#91a5be','font-size':12},n)});let prev=null;entries.filter(e=>Date.parse(e.capturedAt)>=start).forEach(e=>{const x=40+(Date.parse(e.capturedAt)-start)/(now-start)*585,y=180-e.weekRemaining*1.5;if(prev&&e.weekRemaining<=prev.e.weekRemaining+1)add('line',{x1:prev.x,y1:prev.y,x2:x,y2:y,stroke:'#64ded0','stroke-width':3});add('circle',{cx:x,cy:y,r:4,fill:'#64ded0'});prev={e,x,y}});if(!prev)add('text',{x:320,y:110,'text-anchor':'middle',fill:'#91a5be'},'同期すると履歴を表示します')}
async function sync(){const s=settings();if(!s.endpoint||!s.syncKey){$('sync-status').textContent='同期API URLと同期キーを設定してください。';return}try{$('sync-status').textContent='同期中…';const res=await fetch(s.endpoint.replace(/\/$/,'')+'/v1/usage',{headers:{authorization:'Bearer '+s.syncKey},cache:'no-store'});if(!res.ok)throw new Error('HTTP '+res.status);const data=await res.json();entries=Array.isArray(data.entries)?data.entries:[];localStorage.setItem(CACHE,JSON.stringify(entries));$('sync-badge').textContent='同期済み';$('sync-status').textContent='最終同期: '+new Date().toLocaleString();render()}catch(e){$('sync-badge').textContent='同期失敗';$('sync-status').textContent='同期失敗: '+e.message;try{entries=JSON.parse(localStorage.getItem(CACHE)||'[]');render()}catch{}}}
$('save-settings').onclick=()=>{const s={endpoint:$('endpoint').value.trim().replace(/\/$/,''),syncKey:$('sync-key').value.trim()};saveSettings(s);$('sync-status').textContent='設定を保存しました';sync()};$('sync-now').onclick=sync;$('generate-key').onclick=()=>{const a=new Uint8Array(24);crypto.getRandomValues(a);$('sync-key').value=[...a].map(b=>b.toString(16).padStart(2,'0')).join('')};function download(c,t,n){const u=URL.createObjectURL(new Blob([c],{type:t})),a=document.createElement('a');a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}$('backup').onclick=()=>download(JSON.stringify({version:2,entries},null,2),'application/json','cyphonic-usage-v2.json');$('csv').onclick=()=>{const rows=[['captured_at','five_remaining','week_remaining','five_reset_at','week_reset_at','confidence'],...entries.map(e=>[e.capturedAt,e.fiveRemaining,e.weekRemaining,e.fiveResetAt||'',e.weekResetAt||'',e.confidence||''])];download('\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n'),'text/csv;charset=utf-8','cyphonic-usage-v2.csv')};const s=settings();$('endpoint').value=s.endpoint||'';$('sync-key').value=s.syncKey||'';try{entries=JSON.parse(localStorage.getItem(CACHE)||'[]')}catch{}render();sync();setInterval(sync,60000);
